config/routes.rb
Rails.application.routes.draw do

 root to:"courses#index"#, :as => :"Accueil"
 devise_for :users, :controllers => { registrations: 'registrations' }

  resources :courses do
  	resources :comments
  end




  resources :questions# a nettoyer apres
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	validates :user_id, presence: true
	
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order("created_at DESC")
    @question = Question.new
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.new
  end

  # GET /questions/new
  def new

    @question = Question.new
    
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_adds.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
  <article class="media box">
    <figure class="media-left">
      <p class="image is-64x64">
        <img class="is-rounded" src="https://bulma.io/images/placeholders/is-64x64.png">
      </p>
    </figure>
    <div class="media-content">
       <%= render 'questions/form' %>
    </div>
  </article>
  <% end %>


<% @questions.each do | question | %>
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <img class="is-rounded" src="https://bulma.io/images/placeholders/is-64x64.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <strong><%= question.user.Nom_Complet %></strong><br />
          
          <p><%= question.question %></p>
        </div>
        <% if user_signed_in? && current_user.id == question.user_id %>
        <nav class="level">
          <div class="level-left is-mobile">
            <%= link_to question, class: "level-item" do %>
              <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to edit_question_path(question), class: "level-item" do %>
              <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to question, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
                <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
            <% end %>
          </div>
        </nav>
        <% end %>
      </div>
    </article>
  </div>
<% end %>
</div>

app/views/questions/_form.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-6">
				<%= simple_form_for(@question ) do |f| %>
					<%= f.error_notification %>
					<div class="field">
					 <div class="control">  	
					    <%= f.input :question, label: "Quelle est votre question ou votre suggestion ?", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Commencez vos Questions par << Comment >>, << Pourquoi>>, << Que >>, etc...", autofocus: true %>
					 </div>
					</div>
					<%= f.button :submit,'Ajouter Une Question', class: "button is-info is-rounded " %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/questions/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Modifier la question</h1>
				<%= render 'form', question: @question %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Annuler', questions_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/questions/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    <% if user_signed_in?%>
          	
        <%= render 'profile' %>
            
       	<%= render 'feed' %>
       	<%= render 'who-to-follow' %>
       	<%= render 'trend_courses' %>
       	<% else %>
       	<p>veillez-vous connecter d'abord!</p>
          <% end %>      
    </div>
  </div>
</section>

app/views/questions/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Créer une nouvelle question</h1>
					<%= render 'form', question: @question %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', questions_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/questions/show.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Ajouter une Question</h1>
					<%= @question.question %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to '	Annuler',questions_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>