config/routes.rb
Rails.application.routes.draw do

 root to:"courses#index"#, :as => :"Accueil"
 devise_for :users, :controllers => { registrations: 'registrations' }

  resources :courses do
  	resources :comments
  end




  resources :questions# a nettoyer apres
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :owned_course, only: [:edit, :update, :destroy]
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  #impressionist apres a 

  # GET /courses
  # GET /courses.json
  def index

   # @comment = @course.comments.order('created_at asc')
    @courses = Course.all.order("created_at Desc").page params[:page]
    @course = Course.new

  end

  # GET /courses/1
  # GET /courses/1.json
  def show
      #@avatar_course_owner = course.user.avatar   
  end

  # GET /courses/new
  def new
    @course = current_user.course.build
  end

  # GET /courses/1/edit
  def edit
  end
  # remove avatar
  
  # POST /courses
  # POST /courses.json

  def create
    @course = current_user.course.build(course_params)  
      if @course.save
        flash[:success] = "Le cours a été bien ajouter"
        redirect_to root_path
      else
        flash[:alert] = "Votre nouveau cours n'a pas pu être crée !  Veuillez vérifier le formulaire."
        render :new
  
        
      end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
      if @course.update(course_params)
        flash[:sucess] = "Cours mis à jour"
        redirect_to root_path
      else
        flash[:alert] = "Mise à jour échouée..."
        render :edit
      end   
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :description, :corps, :level_course, :material_course, :user_id, :avatar)
    end

    def owned_course
      unless current_user == @courses.user
        flash[:alert] = "Cette action n'est pas possible!"
        redirect_to root_path
    end
end
end

app/helpers/courses_helper.rb
module CoursesHelper

	
end

app/views/courses/_comments_form.html.erb
<div class="comment-form col-sm-11">
 <%= simple_form_for(@comment) do |f| %>
    <%= f.text_field :content, placeholder: 'Ajouter un commentaire...', class: "comment_content" %>
  <%= f.submit 'Ajouter un Commentaire', class: 'comment-submit-button is-rounded' %>
 <% end %>
</div>

app/views/courses/_feed.html.erb
<div class="column is-8 ">
  <% if user_signed_in? %>
    <article class="media box">
      <div class="media-left">
        <figure class="image is-32x32 is-rounded">
           <%= link_to image_tag(current_user.avatar.url(:thumb), alt:current_user.username), edit_user_registration_path, class: "button" %>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <span>
             <% if current_user.status=='1' %>
              <p><%= current_user.username %>, Professeur au <%= current_user.school%> de <%= current_user.city %></p>
              <% else %>
              <p><%= current_user.username %>, Elève de <%= current_user.level_class %> au <%= current_user.school%> de <%= current_user.city %></p>
             <% end %>               
            </span>
            
          </p>
          <p class="content container">
            <%= link_to "Ajouter votre question ou lien ?", new_question_path , class:"is-info" %>
          </p>
        </div>
      </div>
    </article>
  <% end %>
  <div class="media-content">
  <% @courses.each do | course| %>
    <div class="box">
      <!--le titre/!-->
      <div class="title">
        <p><%= course.title %></p>    
      </div><br> 
      <!-- avatar /!-->      
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= link_to image_tag(course.user.avatar.url(:medium), alt:course.user.username), edit_user_registration_path, class: "button" %>
        </div>
        <!--infos createur Nom_complet et son bio/!-->
        <div class="media-content">
          <div class="content">
            <% if course.user.status=='1' %>
              <p><%= course.user.username %>, Professeur au <%= course.user.school%> de <%= course.user.city %></p>
              <% else %>
              <p><%= course.user.username %>, Elève de <%= course.user.level_class %> au <%= course.user.school%> de <%= course.user.city %></p>
              <br>
              <small><%= course.user.bio %></small>
             <% end %>  
          </div>
        </div>
      </article>
      <!--le corps du course /!-->
      <div class="media-content">
        <div class="content">
          <div class="box">
            <%= sanitize course.corps %>
            
          </div>
        </div>
      </div>

      <!--options supplementaires:/!-->
      <% if current_user.id == course.user_id %>
        <nav class="level">
          <div class="level-left is-mobile is-right">
            <%= link_to course, class: "level-item" do %>
              <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to edit_course_path(course), class: "level-item" do %>
              <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to course, method: :delete, data: { confirm: "Etes-vous sûre de vouloir supprimez ?" } do %>
                <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
            <% end %> 
          </div>              
        </nav>
      <% end %>
      <!--affiché les commentaires deja cree /!-->
      <!--soumettre le formulaire de commentaire/!-->
      
    </div>
  <% end %>
  </div>
</div>

app/views/courses/_follow.html.erb
<div class="column is-2">
	<nav class="panel">
		<p class="panel-heading">connexion +</p>
	
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	</nav>
</div>

app/views/courses/_form.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">

    <%= simple_form_for(@course) do |f| %>
      <%= f.error_notification %>

          <div class="field">
            <div class="control">
              <%= f.input :title, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" },class:"active", placeholder: "Donnez un titre qui attire l'attention", label:"Titre du cours:" %>
            </div>
          </div>


        <div class="columns">
          <div class="field column is-6">
            <div class="control">
              <label class="label">Niveau :</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :level_course, collection: Course::NIVEAUX, prompt: "Selectionne le niveau", label:"Niveau du cours:" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-briefcase"></i>
                </span>
              </div>
            </div>
          </div>   

          <div class="field column is-6">
            <div class="control">
              <label class="label">Matière:</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :material_course, collection: Course::MATIERES, prompt: "Selectionne la matère", label:"Selectionne la matiere" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-briefcase"></i>
                </span>
              </div>
            </div>
          </div>   
        </div>

        

        <div class="field">
            <div class="control">
             <%= f.input :corps, required: true, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" }, label:'corps du sujet' %>
             
            </div>
        </div>
        <div class="field">
            <div class="control">
             <%= f.input :description, required: true, input_html: { class: "textarea" }, wrapper: false, label_html: { class: "label" }, label:'la description du sujet' %>
             
            </div>
        </div>
        <%= f.button :submit," Créer le Doc" ,class: "button is-info is-large is-rounded" %>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/courses/_matieres.html.erb
<div class="colmun is-4">
	<nav class="panel">
		<p class="panel-heading">Fil Matières</p>

		<a class="panel-block">
			<span class="media-content">
				<span class="content">
					<%= link_to 'Histoire', courses_path(:matiere_course => "Histoire") %>
				</span>
			</span>
		</a>
		<a class="panel-block">
			<span class="media-content">
				<span class="content">
					<%= link_to 'Histoire', courses_path(:matiere_course => "Histoire") %>
				</span>
			</span>
		</a>
		<a class="panel-block">
			<span class="media-content">
				<span class="content">
					<%= link_to 'Histoire', courses_path(:matiere_course => "Histoire") %>
				</span>
			</span>
		</a>
		<a class="panel-block">
			<%= link_to 'Géographie', courses_path(:matiere_course => "Géographie") %>
		</a>
		<a class="panel-block">
			<%= link_to 'Math', courses_path(:matiere_course => "Math") %>
		</a>
		<a class="panel-block">
			<%= link_to 'Physiques', courses_path(:matiere_course => "Physiques") %>
		</a>
		<a class="panel-block">
			<%= link_to 'Chimie', courses_path(:matiere_course => "Chimie") %>
		</a>
		<a class="panel-block"> 
			<%= link_to 'SVT', courses_path(:matiere_course => "SVT") %>
		</a>
		<a class="panel-block">
			<%= link_to 'Français', courses_path(:matiere_course => "Français") %>
		</a>
		<a class="panel-block"> 
			<%= link_to 'Anglais', courses_path(:matiere_course => "Anglais") %>
		</a>
		<a class="panel-block"> 
			<%= link_to 'Philosophie', courses_path(:matiere_course => "Philosophie") %>
		</a>
		<a class="panel-block">
			<%= link_to 'EDHC', courses_path(:matiere_course => "EDHC") %>
		</a>
		<a class="panel-block">
			<%= link_to 'Allemand', courses_path(:matiere_course => "Allemand") %>
		</a>
		<a class="panel-block">
			<%= link_to 'Espagnol', courses_path(:matiere_course => "Espagnol") %>
		</a>
		<a class="panel-block">
			<%= link_to 'Entreprenariat', courses_path(:matiere_course => "Entreprenariat") %>
		</a>
		<a class="panel-block">
			<%= link_to 'Art Plastique', courses_path(:matiere_course => "Art-Plastique") %>
		</a>
	</nav>
</div>

app/views/courses/_profile.html.erb
<div class="column is-left is-one-third is-vcentered">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<img src="https://bulma.io/images/placeholders/64x64.png">
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p><%= current_user.Nom_Complet %>, <%= current_user.bio %></p>
						
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div has-centered-text>
						<p class="heading"><i class="fas fa-friends">Amis</i></p>
						<p class="subtitle is-6 "><%= current_user.questions.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div has-centered-text>
						<p class="heading">Cours</p>
						<p class="subtitle is-6 "><%= current_user.course.count %></p>
					</div>
				</div>
			</div>
		</div>
		


	</nav>	
	
</div>

app/views/courses/_who-to-follow.html.erb
<div class="column  is-vcentered">
	<nav class="panel">
		<p class="panel-heading">Plus de connexion</p>
	
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	</nav>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<div class="notification">
    <section class="section is-mobile">
        <div class="container is-centered">
            
                <% if user_signed_in?%>        
                    <%= render 'feed' %>
                <% else %>
                     <%= render template: 'home/index' %>
                <% end %>      
           
        </div>
    </section>
</div>

app/views/courses/new.html.erb
<h1 style="text-align: center;">Ajouter un cours</h1>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
      	<div class="subtitle">
      		<%= @course.title %>
      	</div>

		<article class="media">
	        <div class="media-left">
	          <figure class="image">
	            <%= link_to image_tag(@course.user.avatar.url(:medium), alt:@course.user.username), edit_user_registration_path, class: "button" %>
	        </div>
	        <!--infos createur Nom_complet et son bio/!-->
	        <div class="media-content">
	          <div class="content">
	            <% if @course.user.status=='1' %>
	              <p><%= @course.user.username %>, Professeur au <%= @course.user.school%> de <%= @course.user.city %></p>
	              <% else %>
	              <p><%= @course.user.username %>, Elève de <%= @course.user.level_class %> au <%= @course.user.school%> de <%= @course.user.city %></p>
	              <br>
	              <small><%= @course.user.bio %></small>
	             <% end %>  
	          </div>
	        </div>
      	</article>
      		
      	<br>

      	<span class="content container">
      		<span class="box">
      			<%= sanitize @course.corps %>
      		</span>
      	</span>

	  </div>
	 
	</div>
 </div>
</div>